package application;

import java.io.IOException;

import com.cognixia.contactManager.controller.UserController;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.MenuBar;
import javafx.stage.Stage;

public class ActionsController {
	
	@FXML
	private MenuBar addMenuBar;
	
	// Event Listener on MenuItem.onAction
	@FXML
	public void navigateHome(ActionEvent event) {
		
		Stage dashBoardWindow = (Stage) addMenuBar.getScene().getWindow();
		
		try {
			
			Parent root = FXMLLoader.load(getClass().getResource("ContactList.fxml"));
			Scene login = new Scene(root);
			
			
			dashBoardWindow.setScene(login);
			
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
	}
	// Event Listener on MenuItem.onAction
	@FXML
	public void addContactClicked(ActionEvent event) {
		Stage dashBoardWindow =  (Stage) addMenuBar.getScene().getWindow();
		
		try {
			Parent root = FXMLLoader.load(getClass().getResource("AddContactScene.fxml"));
			Scene addContact = new Scene(root);
			dashBoardWindow.setScene(addContact);
			
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
	}
	// Event Listener on MenuItem.onAction
	@FXML
	public void updateContactClicked(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem.onAction
	@FXML
	public void deleteContactClicked(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem.onAction
	@FXML
	public void logoutClicked(ActionEvent event) {
		Stage dashBoardWindow = (Stage) addMenuBar.getScene().getWindow();
		
		try {
			
			Parent root = FXMLLoader.load(getClass().getResource("MainScene.fxml"));
			Scene login = new Scene(root);
			
			UserController.setActiveUser(null);
			
			dashBoardWindow.setScene(login);
			
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
}
