package application;

import java.io.IOException;

import com.cognixia.contactManager.controller.UserController;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.MenuItem;
import javafx.scene.control.TableView;
import javafx.stage.Stage;

public class ContactListController {
	
	
	@FXML
	private TableView<String> contactTable;
	
	@FXML
	private MenuItem miLogout;
	
	
	@FXML
	public void logoutClicked(ActionEvent event) {
		Stage dashBoardWindow = (Stage) contactTable.getScene().getWindow();
		
		
		try {
			
			Parent root = FXMLLoader.load(getClass().getResource("MainScene.fxml"));
			Scene login = new Scene(root);
			
			UserController.setActiveUser(null);
			
			dashBoardWindow.setScene(login);
			
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	

	// Event Listener on Button.onAction
	@FXML
	public void addContactClicked(ActionEvent event) {
		
		Stage dashBoardWindow =  (Stage) contactTable.getScene().getWindow();
		
//		try {
//			Parent root = FXMLLoader.load(getClass().getResource("ContactList.fxml"));
//			Scene dashboard = new Scene(root);
//			dashBoardWindow.setScene(dashboard);
//			
//		} catch (IOException e) {
//			// TODO Auto-generated catch block
//			e.printStackTrace();
//		}
	}
	// Event Listener on Button.onAction
	@FXML
	public void updateContactClicked(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void deleteContactClicked(ActionEvent event) {
		// TODO Autogenerated
	}
}
